/**
 * @description authentication actions
 */
export const LOGIN_INPUT_CHANGE = "HANDLE_LOGIN_TEXT_INPUT";
export const SUBMITTING_LOGIN_CREDENTIALS = "IS_SUBMITTING_LOGIN_CREDENTIALS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESSFULLY";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

/**
 * @description social authentication
 */
export const CANCEL_SOCIAL_AUTH = "CANCEL_SOCIAL_AUTH";
export const IS_OPENING_SOCIAL_AUTH_PROVIDER = "IS_OPEN_SOCIAL_AUTH_PROVIDER";
export const SUBMITTING_SOCIAL_AUTH = "SUBMITTING_SOCIAL_AUTH";
export const SETTING_TOKEN_SOCIAL_AUTH = "SETTING_TOKEN_SOCIAL_AUTH";
export const SOCIAL_AUTH_SUCCESS = "SOCIAL_AUTH_SUCCESS";
export const SOCIAL_AUTH_FAILED = "SOCIAL_AUTH_FAILED";

/**
 * @description fetch article action types
 */
export const ARTICLE_FETCHED = "FETCH_ARTICLE";
export const FETCHING_ARTICLE = "FETCHING_ARTICLE";
export const FETCHING_ASIDE_ARTICLES = "FETCHING_ASIDE_ARTICLES";

/**
 * @description deleting action types
 */
export const ARTICLE_ERROR = "ARTICLE_ERROR";
export const DELETE_ARTICLE = "DELETE_ARTICLE";

/**
 * @description search and filter action types
 */
export const SEARCHING_ARTICLES = "FETCHING_ARTICLE";
export const ARTICLE_SEARCH_SUCCESS = "ARTICLE_SEARCH_SUCCESSFULLY";
export const ARTICLE_SEARCH_FAILED = "ARTICLE_SEARCH_FAILED";
export const SEARCH_QUERY_CHANGE = "SEARCH_QUERY_CHANGE";
export const CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS";
export const SET_SUGGESTED_ARTICLES = "SET_SUGGESTED_ARTICLES";

/**
 * @description following action types
 */
export const FOLLOWING_SUCCESS = "FOLLOWING_SUCCESS";
export const WAITING_RESPONSE = "WAITING_RESPONSE";
export const FOLLOWING_FAILED = "FOLLOWING_FAILED";

/**
 * @description notification action types
 */
export const FETCHING_NOTIFICATION = "FETCHING_NOTIFICATION";
export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
export const NOTIFICATION_FAILED = "NOTIFICATION_FAILED";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";

/*
 * @description registration action creator
 */
export const REGISTER_REQUESTED = "REGISTER_REQUESTED";
export const REGISTER_REQUEST_LOADING = "REGISTER_REQUEST_LOADING";
export const REGISTER_REQUEST_SUCCEEDED = "REGISTER_REQUEST_SUCCEEDED";
export const REGISTER_REQUEST_FAILED = "REGISTER_REQUEST_FAILED";
export const REGISTER_INPUT_CHANGE = "REGISTER_INPUT_CHANGE";
export const REGISTER_VALIDATE_INPUT = "REGISTER_VALIDATE_INPUT";
